### ISSUE TITLE
Any Technical details explanation?

### ISSUE THREAD

**Issue by hooke007** [cunnyplapper/CuNNy#1]
I'm curcious why it was firstly doubled by FSR.

**Comment by cunnyplapper** [comment]
I thought the FSR's output looked quite nice and I liked how it dealt with lines. But by default RCAS can over-shapen a bit and doesn't deal with some cases (like text) nicely so I tried strapping a CNN onto it and ended up with results that I personally am quite pleased with.

**Comment by cunnyplapper** [comment]
I stopped using FSR since I changed to a new dataset.
